SELECT
    HC.*,
    C.TELEFONE,
    ASSU.NOME ASSUNTO,
    ATEN.NOME ATENDIMENTO
FROM
    HISTORICO_CONVERSA HC
    INNER JOIN CLIENTES C ON HC.CLIENTE_ID = C.ID
    INNER JOIN HISTORICO_CONVERSA_TIPO_ASSUNTO ASSU ON HC.HISTORICO_CONVERSA_TIPO_ASSUNTO_ID = ASSU.ID
    INNER JOIN HISTORICO_CONVERSA_TIPO_ATENDIMENTO ATEN ON HC.HISTORICO_CONVERSA_ATENDIMENTO_ID = ATEN.ID
WHERE
    C.TELEFONE = '51999731290'
ORDER BY
    HC.DATA_REGISTRO DESC